services:
  php:
    build: .
    container_name: php_test
    volumes:
      - .:/app
    working_dir: /app
    environment:
      XDEBUG_MODE: "develop,debug,coverage"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    entrypoint:
      ["composer", "test-coverage"]
